name: "BATS"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@master
        with:
          bats-version: 1.1.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: Test
        run: cd tests && bats *.bats